
---

- name: Add info
  hosts: nodes
  become: yes

  tasks:
  - name: net ifnames
    replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
        replace: '\1 {{ option }}={{ value }}\2'
    vars:
        option: net.ifnames
        value: 0

  - name: biosdevname
    replace:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
        replace: '\1 {{ option }}={{ value }}\2'
    vars:
        option: biosdevname
        value: 0

  - name: Write grub configuration file
    command: grub2-mkconfig -o /boot/grub2/grub.cfg

...